### ISSUE TITLE
Error trying to install the sdk via composer

### ISSUE THREAD

**Issue by ReynerHL** [Facturama/facturama-php-sdk#11]
Local Enviroment:
OS: Windows 10
PHP: PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 )
composer: **1.6.4** 2018-04-13 12:04:24

Issuing the line you propose for install the package launch us an error:
$ composer install facturama/facturama-php-sdk
Invalid argument facturama/facturama-php-sdk. Use "composer require facturama/facturama-php-sdk" instead to add packages to your composer.json.

Some days ago, I was able to install the SDK specifying a custom branch:
composer require facturama/facturama-php-sdk dev-master

But after seeing you are making changes in the SDK I would like to use tha latest version.

Thanks in advance for your help.

**Comment by phansys** [comment]
Since this package have no releases yet, you must install a dev version. Please, note that the command you must run is `composer require` instead of `composer install`:
```
composer require facturama/facturama-php-sdk:^2.0@dev
```
