### ISSUE TITLE
El campo DomicilioFiscalReceptor del receptor

### ISSUE THREAD

**Issue by oswaldo89** [Facturama/facturama-php-sdk#33]
Estoy integrando su libreria, de momento estoy accediendo a la cuenta de prueba que proporcionan en su PDF
`base64_encode('pruebas:pruebas2011')`, parece que ya hace la conexion correctamente, pero tomando el ejemplo de su documentacion, eh incluso de la documentacion de la web oficial... me marca este error

`"Message" => "El campo DomicilioFiscalReceptor del receptor, 
debe encontrarse en la lista de RFC inscritos no cancelados en el SAT."`

```
$params =  [
            "Receiver" => [
                "Name" => "UNIVERSIDAD ROBOTICA ESPAÑOLA", 
                "CfdiUse" => "G03", 
                "Rfc" => "URE180429TM6", 
                "FiscalRegime" => "601", 
                "TaxZipCode" => "65000" 
            ], 
            "CfdiType" => "I", 
            "NameId" => "1", 
            "ExpeditionPlace" => "78240", 
            "Serie" => null, 
            "Folio" => "V8", 
            "PaymentForm" => "01", 
            "PaymentMethod" => "PUE", 
            "Exportation" => "01", 
            "Items" => [
                     [
                        "Quantity" => "1", 
                        "ProductCode" => "10111302", 
                        "UnitCode" => "H87", 
                        "Unit" => "Pieza", 
                        "Description" => "producto prueba cfdi4.0", 
                        "IdentificationNumber" => "papc40", 
                        "UnitPrice" => "1.00", 
                        "Subtotal" => "1.00", 
                        "TaxObject" => "02", 
                        "Taxes" => [
                           [
                              "Name" => "IVA", 
                              "Rate" => "0.16", 
                              "Total" => "0.16", 
                              "Base" => "1", 
                              "IsRetention" => "false", 
                              "IsFederalTax" => "true" 
                           ] 
                        ], 
                        "Total" => "1.16" 
                     ] 
                  ] 
         ]; 
```

Saben de que manera lo puedo resolver.. en sandbox ?

**Comment by DagoGzz** [comment]
Me esta sucediendo lo mismo, al parecer se refiere al parámetro "TaxZipCode" que no coincide con el RFC.

**Comment by DagoGzz** [comment]
@oswaldo89 puedes intentar con alguno de estos: 
https://apisandbox.facturama.mx/guias/conocimientos/sellos-digitales-pruebas

Por ejemplo este si funciona

`'Receiver' => [
                'Rfc' => 'FUNK671228PH6',
                'Name' => 'KARLA FUENTE NOLASCO',
                'CfdiUse' => 'D01',
                'TaxZipCode' => '01160',
                'FiscalRegime' => '605',
            ]`

**Comment by DagoGzz** [comment]
Acabo de hablar con soporte y me comentaron que el TaxZipCode cambio recientemente a 86991

**Comment by oswaldo89** [comment]
muchas gracias, con ese nuevo zipcode ya funciona
